/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ControllerConsole_Controller */

#ifndef _Included_ControllerConsole_Controller
#define _Included_ControllerConsole_Controller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ControllerConsole_Controller
 * Method:    controller_open
 * Signature: (IB)J
 */
JNIEXPORT jlong JNICALL Java_ControllerConsole_Controller_controller_1open
  (JNIEnv *, jobject, jint, jbyte);

/*
 * Class:     ControllerConsole_Controller
 * Method:    controller_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ControllerConsole_Controller_controller_1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ControllerConsole_Controller
 * Method:    ochannel_add
 * Signature: (JLjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_ControllerConsole_Controller_ochannel_1add
  (JNIEnv *, jobject, jlong, jstring, jint, jint);

/*
 * Class:     ControllerConsole_Controller
 * Method:    obit_add
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ControllerConsole_Controller_obit_1add
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ControllerConsole_Controller
 * Method:    opulse_add
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ControllerConsole_Controller_opulse_1add
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ControllerConsole_Controller
 * Method:    ochannel_get_value
 * Signature: (JI)B
 */
JNIEXPORT jbyte JNICALL Java_ControllerConsole_Controller_ochannel_1get_1value
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ControllerConsole_Controller
 * Method:    ochannel_set_value
 * Signature: (JIB)V
 */
JNIEXPORT void JNICALL Java_ControllerConsole_Controller_ochannel_1set_1value
  (JNIEnv *, jobject, jlong, jint, jbyte);

/*
 * Class:     ControllerConsole_Controller
 * Method:    ochannel_write
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ControllerConsole_Controller_ochannel_1write
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ControllerConsole_Controller
 * Method:    obit_get_value
 * Signature: (JI)B
 */
JNIEXPORT jbyte JNICALL Java_ControllerConsole_Controller_obit_1get_1value
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ControllerConsole_Controller
 * Method:    obit_set_value
 * Signature: (JIB)V
 */
JNIEXPORT void JNICALL Java_ControllerConsole_Controller_obit_1set_1value
  (JNIEnv *, jobject, jlong, jint, jbyte);

/*
 * Class:     ControllerConsole_Controller
 * Method:    opulse_out
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_ControllerConsole_Controller_opulse_1out
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     ControllerConsole_Controller
 * Method:    ichannel_add
 * Signature: (JLjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_ControllerConsole_Controller_ichannel_1add
  (JNIEnv *, jobject, jlong, jstring, jint, jint);

/*
 * Class:     ControllerConsole_Controller
 * Method:    ichannel_get_value
 * Signature: (JI)B
 */
JNIEXPORT jbyte JNICALL Java_ControllerConsole_Controller_ichannel_1get_1value
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ControllerConsole_Controller
 * Method:    ichannel_read
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_ControllerConsole_Controller_ichannel_1read
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
